var phoneModel = [
  {
    "title": "",
    "name": "hongmi-2",
    "fileName": "hongmi-2.png",
    "model": "红米2",              //手机型号，需要对应后端数据库的“分类”
    "phonePackage": "",            //套餐
    "layout": "竖版",              //版式
    "width": 881,                  //整张模版图的宽度
    "height": 1627,
    "isAuto": true,                //是否由程序自动处理，false的话程序会跳过此款机型
    "isUpload": true,              //备用
    "doubleCheck": false,          //备用
    "qrcodeArea": {                //二维码区域（不包含二维码背景）
      "width": 180,                //二维码区域的宽度
      "height": 180,
      "x": "",                     //相对于二维码背景，二维码区域的x座标
      "y": "",
      "bgColor": "",               //二维码区域底色
      "hotPixelColor": ""          //二维码区域噪点色
    },
    "notes": ""                    //备注
  },
  {
    "title": "",
    "name": "hongmi-3",
    "fileName": "hongmi-3.png",
    "model": "红米3",
    "phonePackage": "",
    "layout": "竖版",
    "width": 850,
    "height": 1689,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "hongmi-note",
    "fileName": "hongmi-note.png",
    "model": "红米note",
    "phonePackage": "",
    "layout": "竖版",
    "width": 957,
    "height": 1819,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "hongmi-note3",
    "fileName": "hongmi-note3.png",
    "model": "红米NOTE3",
    "phonePackage": "",
    "layout": "竖版",
    "width": 909,
    "height": 1807,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "背面下方有喇叭位"
  },
  {
    "title": "",
    "name": "huawei-mate7",
    "fileName": "huawei-mate7.png",
    "model": "华为mate7",
    "phonePackage": "",
    "layout": "竖版",
    "width": 1155,
    "height": 2053,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "huawei-mate8",
    "fileName": "huawei-mate8.png",
    "model": "华为mate8",
    "phonePackage": "",
    "layout": "竖版",
    "width": 969,
    "height": 1795,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "huawei-mate-S",
    "fileName": "huawei-mate-S.png",
    "model": "华为mates",
    "phonePackage": "",
    "layout": "竖版",
    "width": 886,
    "height": 1772,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "huawei-p8-gaopei",
    "fileName": "huawei-p8-gaopei.png",
    "model": "华为P8高配版",
    "phonePackage": "",
    "layout": "竖版",
    "width": 1008,
    "height": 1816,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "huawei-p8-qinchun",
    "fileName": "huawei-p8-qinchun.png",
    "model": "华为P8青春版",
    "phonePackage": "",
    "layout": "竖版",
    "width": 850,
    "height": 1689,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "huawei-p9",
    "fileName": "huawei-p9.png",
    "model": "华为P9",
    "phonePackage": "",
    "layout": "竖版",
    "width": 850,
    "height": 1689,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "huawei-p9-plus",
    "fileName": "huawei-p9-plus.png",
    "model": "华为P9plus",
    "phonePackage": "",
    "layout": "竖版",
    "width": 954,
    "height": 1854,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  }, 
  {
    "title": "",
    "name": "iphone-4",
    "fileName": "iphone-4.png",
    "model": "iphone4/4s",
    "phonePackage": "",
    "layout": "竖版",
    "width": 743,
    "height": 1448,
    "isAuto": false,
    "isUpload": true,
    "doubleCheck": true,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": undefined,
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "iphone-5",
    "fileName": "iphone-5.png",
    "model": "iphone5/5s",
    "phonePackage": "",
    "layout": "竖版",
    "width": 773,
    "height": 1523,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "iphone-6",
    "fileName": "iphone-6.png",
    "model": "iphone6/6s",
    "phonePackage": "",
    "layout": "竖版",
    "width": 900,
    "height": 1724,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "iphone-6-plus",
    "fileName": "iphone-6-plus.png",
    "model": "iphone6/6s plus",
    "phonePackage": "",
    "layout": "竖版",
    "width": 962,
    "height": 1914,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "iphone-7",
    "fileName": "iphone-7.png",
    "model": "iphone7",
    "phonePackage": "",
    "layout": "竖版",
    "width": 900,
    "height": 1724,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "iphone6 和 iphone7 尺寸相同"
  },
  {
    "title": "",
    "name": "letv-1s",
    "fileName": "letv-1s.png",
    "model": "乐视1s",
    "phonePackage": "",
    "layout": "竖版",
    "width": 1067,
    "height": 1895,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "letv-2",
    "fileName": "letv-2.png",
    "model": "xxxxx",
    "phonePackage": "",
    "layout": "竖版",
    "width": 954,
    "height": 1835,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "meilan-note3",
    "fileName": "meilan-note3.png",
    "model": "魅蓝note3",
    "phonePackage": "",
    "layout": "竖版",
    "width": 898,
    "height": 1831,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "meizu-mx5",
    "fileName": "meizu-mx5.png",
    "model": "魅族MX5",
    "phonePackage": "",
    "layout": "竖版",
    "width": 978,
    "height": 1853,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "oppo-r7",
    "fileName": "oppo-r7.png",
    "model": "oppoR7",
    "phonePackage": "",
    "layout": "竖版",
    "width": 926,
    "height": 1745,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },  
  {
    "title": "",
    "name": "oppo-r7plus",
    "fileName": "oppo-r7plus.png",
    "model": "oppo-r7plus",
    "phonePackage": "",
    "layout": "竖版",
    "width": 992,
    "height": 1890,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "oppo-r7s",
    "fileName": "oppo-r7s.png",
    "model": "oppo-r7s",
    "phonePackage": "",
    "layout": "竖版",
    "width": 926,
    "height": 1851,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "oppo-r9",
    "fileName": "oppo-r9.png",
    "model": "oppo r9",
    "phonePackage": "",
    "layout": "竖版",
    "width": 898,
    "height": 1795,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "oppo-r9-plus",
    "fileName": "oppo-r9-plus.png",
    "model": "oppo-r9plus",
    "phonePackage": "",
    "layout": "竖版",
    "width": 969,
    "height": 1937,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "rongyao-4A",
    "fileName": "rongyao-4A.png",
    "model": "荣耀4A",
    "phonePackage": "",
    "layout": "竖版",
    "width": 862,
    "height": 1701,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "rongyao-4c",
    "fileName": "rongyao-4c.png",
    "model": "荣耀4C",
    "phonePackage": "",
    "layout": "竖版",
    "width": 986,
    "height": 1777,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "rongyao-6",
    "fileName": "rongyao-6.png",
    "model": "荣耀6",
    "phonePackage": "",
    "layout": "竖版",
    "width": 885,
    "height": 1730,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "rongyao-6-plus",
    "fileName": "rongyao-6-plus.png",
    "model": "荣耀6PLUS",
    "phonePackage": "",
    "layout": "竖版",
    "width": 965,
    "height": 1874,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "rongyao-7",
    "fileName": "rongyao-7.png",
    "model": "荣耀7",
    "phonePackage": "",
    "layout": "竖版",
    "width": 1004,
    "height": 1784,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "闪光灯在右"
  },
  {
    "title": "",
    "name": "rongyao-7i",
    "fileName": "rongyao-7i.png",
    "model": "荣耀7i",
    "phonePackage": "",
    "layout": "竖版",
    "width": 898,
    "height": 1747,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "rongyao-v8",
    "fileName": "rongyao-v8.png",
    "model": "xxxxx",
    "phonePackage": "",
    "layout": "竖版",
    "width": 945,
    "height": 1878,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "samsumg-A7",
    "fileName": "samsumg-A7.png",
    "model": "三星A7",
    "phonePackage": "",
    "layout": "竖版",
    "width": 909,
    "height": 1878,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "samsumg-S6",
    "fileName": "samsumg-S6.png",
    "model": "三星S6",
    "phonePackage": "",
    "layout": "竖版",
    "width": 850,
    "height": 1701,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "平面机G9200, 闪光灯在右"
  }, 
  {
    "title": "",
    "name": "sumsamg-S6-edge",
    "fileName": "sumsamg-S6-edge.png",
    "model": "三星S6 Edge",
    "phonePackage": "",
    "layout": "竖版",
    "width": 839,
    "height": 1713,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "曲面机G9280, 闪光灯在右"
  },
  {
    "title": "",
    "name": "samsumg-S6-edge-plus",
    "fileName": "samsumg-S6-edge-plus.png",
    "model": "三星S6-edge-plus",
    "phonePackage": "",
    "layout": "竖版",
    "width": 921,
    "height": 1831,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "曲面机G9280, 闪光灯在右"
  },
  {
    "title": "",
    "name": "sumsumg-S7",
    "fileName": "sumsumg-S7.png",
    "model": "三星S7",
    "phonePackage": "",
    "layout": "竖版",
    "width": 850,
    "height": 1665,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "闪光灯在右"
  },
  {
    "title": "",
    "name": "samsumg-S7-edge",
    "fileName": "samsumg-S7-edge.png",
    "model": "三星S7 edge",
    "phonePackage": "",
    "layout": "竖版",
    "width": 862,
    "height": 1760,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": "曲面机, 闪光灯在右"
  },  
  {
    "title": "",
    "name": "vivo-v3",
    "fileName": "vivo-v3.png",
    "model": "vivo-v3",
    "phonePackage": "",
    "layout": "竖版",
    "width": 862,
    "height": 1707,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "vivo-v3-max",
    "fileName": "vivo-v3-max.png",
    "model": "vivo-v3-max",
    "phonePackage": "",
    "layout": "竖版",
    "width": 921,
    "height": 1843,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "vivo-x6",
    "fileName": "vivo-x6.png",
    "model": "vivo-x6",
    "phonePackage": "",
    "layout": "竖版",
    "width": 922,
    "height": 1784,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "vivo-x6-plus",
    "fileName": "vivo-x6-plus.png",
    "model": "vivo-x6-plus",
    "phonePackage": "",
    "layout": "竖版",
    "width": 969,
    "height": 1878,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "vivo-xplay-5",
    "fileName": "vivo-xplay-5.png",
    "model": "vivo-xplay5",
    "phonePackage": "",
    "layout": "竖版",
    "width": 922,
    "height": 1784,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "xiaomi-4",
    "fileName": "xiaomi-4.png",
    "model": "小米4",
    "phonePackage": "",
    "layout": "竖版",
    "width": 927,
    "height": 1725,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "xiaomi-4c",
    "fileName": "xiaomi-4c.png",
    "model": "小米4C",
    "phonePackage": "",
    "layout": "竖版",
    "width": 886,
    "height": 1724,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "xiaomi-5",
    "fileName": "xiaomi-5.png",
    "model": "小米5",
    "phonePackage": "",
    "layout": "竖版",
    "width": 873,
    "height": 1807,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "xiaomi-max",
    "fileName": "xiaomi-max.png",
    "model": "小米max",
    "phonePackage": "",
    "layout": "竖版",
    "width": 1063,
    "height": 2067,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
  {
    "title": "",
    "name": "xiaomi-note",
    "fileName": "xiaomi-note.png",
    "model": "小米note",
    "phonePackage": "",
    "layout": "竖版",
    "width": 1029,
    "height": 1924,
    "isAuto": true,
    "isUpload": true,
    "doubleCheck": false,
    "qrcodeArea": {
      "width": 180,
      "height": 180,
      "x": "",
      "y": "",
      "bgColor": "",
      "hotPixelColor": ""
    },
    "notes": ""
  },
];
